# Generated by Django 2.0.5 on 2019-05-21 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 21, 15, 55, 12, 687865, tzinfo=utc), help_text='date/time when this row was first created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date/time this row was last updated'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 21, 15, 55, 18, 521564, tzinfo=utc), help_text='date/time when this row was first created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date/time this row was last updated'),
        ),
        migrations.AddField(
            model_name='userrecent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 21, 15, 55, 30, 479002, tzinfo=utc), help_text='date/time when this row was first created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrecent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date/time this row was last updated'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='_common.UserFavorite'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='recents',
            field=models.ManyToManyField(blank=True, null=True, to='_common.UserRecent'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('dark', 'dark'), ('light', 'light')], help_text='name of theme to user for this user', max_length=16, null=True),
        ),
    ]
