# Generated by Django 2.0.5 on 2019-05-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_common', '0003_auto_20190522_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='name',
            field=models.CharField(blank=True, help_text='name/label/reference for this favorite', max_length=32, null=True),
        ),
    ]
