# Generated by Django 2.0.5 on 2019-04-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time this row was last updated')),
                ('hostname', models.CharField(help_text='unique fqdn of a host', max_length=64, unique=True)),
                ('lock_state', models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='unlocked', max_length=16)),
            ],
            options={
                'db_table': 'hostlock_hosts',
            },
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date/time when this row was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date/time this row was last updated')),
                ('requester', models.CharField(blank=True, help_text='entity requesting this lock', max_length=128, null=True)),
                ('source', models.CharField(blank=True, help_text='location this lock was requested from', max_length=128, null=True)),
                ('request_details', models.CharField(blank=True, help_text='details of the request', max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, help_text='details regarding this lock request', max_length=254, null=True)),
                ('notes', models.CharField(blank=True, help_text='additional notes regarding this lock', max_length=255, null=True)),
                ('expiration', models.IntegerField(blank=True, default=900, help_text='time (in seconds) from creation that this lock will expire', null=True)),
                ('status', models.CharField(choices=[('granted', 'granted'), ('released', 'released'), ('manually released', 'manually released'), ('expired', 'expired')], default='unknown', help_text='current status of this lock', max_length=16)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostlock.Host')),
            ],
            options={
                'db_table': 'hostlock_logs',
            },
        ),
    ]
