# Generated by Django 2.0.5 on 2019-04-23 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('hostlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='group that owns this host', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
