# Generated by Django 2.0.5 on 2019-04-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0002_host_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='user requesting this lock', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
