# Generated by Django 2.0.5 on 2019-04-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0004_auto_20190423_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lock',
            table='hostlock_locks',
        ),
    ]
