# Generated by Django 2.0.5 on 2019-05-05 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0006_auto_20190505_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='no_expire',
            field=models.BooleanField(default=False, help_text='set to True if this lock does not expire'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 5, 22, 40, 39, 868839, tzinfo=utc), help_text='date/time when this lock expires', null=True),
        ),
    ]
