# Generated by Django 2.0.5 on 2019-05-07 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0007_auto_20190505_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 7, 15, 50, 37, 943421, tzinfo=utc), help_text='date/time when this lock expires', null=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='status',
            field=models.CharField(choices=[('granted', 'granted'), ('released', 'released'), ('manually released', 'manually released'), ('expired', 'expired')], default='unknown', help_text='current status of this lock', max_length=32),
        ),
    ]
