# Generated by Django 2.0.5 on 2019-05-07 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0008_auto_20190507_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='extend_count',
            field=models.IntegerField(default=0, help_text='number of times this lock has been extended'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 0, 6, 49, 188580, tzinfo=utc), help_text='date/time when this lock expires', null=True),
        ),
    ]
