# Generated by Django 2.0.5 on 2019-05-07 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0010_auto_20190507_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 0, 7, 8, 31645, tzinfo=utc), help_text='date/time when this lock expires', null=True),
        ),
    ]
