# Generated by Django 2.0.5 on 2019-05-29 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostlock', '0011_auto_20190507_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 4, 22, 7, 483077, tzinfo=utc), help_text='date/time when this lock expires', null=True),
        ),
    ]
